from Areas import *

area = Areas()
print(area.triangulo1(10,15))
perimetro = PerimetrosReg()
res = area.circulo(1)
print(res)
res = area.triangulo1(2,2)
print(res)
res = perimetro.Cuadrilatero(2,3)
print(res)
res = perimetro.Trilangulo(2,3,5)
print(res)
res = perimetro.Circulo(2)
print(res)
